from __future__ import annotations

import logging

from ..extensions import db
from ..models import ExpenseCategory, ProductionMachine

logger = logging.getLogger("ttech.defaults")


DEFAULT_MACHINES = [
    {"machine_ref": "MCH-PVC-01", "name": "Pebble Evolis Card Printer", "category": "PVC Cards", "capability": "PVC ID cards and card printing", "image_path": "/machines/pvc-card.svg"},
    {"machine_ref": "MCH-SUB-01", "name": "Sublimation Printer", "category": "Sublimation", "capability": "Mug cups and coated gift items", "image_path": "/machines/sublimation.svg"},
    {"machine_ref": "MCH-UVDTF-01", "name": "UV DTF Printer", "category": "UV DTF", "capability": "Assorted / other UV DTF items", "image_path": "/machines/uv-dtf.svg"},
    {"machine_ref": "MCH-LF-01", "name": "Large Format Printer", "category": "Large Format", "capability": "Banners and stickers", "image_path": "/machines/large-format.svg"},
    {"machine_ref": "MCH-DTF-01", "name": "DTF Printer", "category": "DTF Apparel", "capability": "T-shirts, diaries and other DTF items", "image_path": "/machines/dtf.svg"},
    {"machine_ref": "MCH-PLOT-01", "name": "Plotter", "category": "Cutting", "capability": "Cutting stencils", "image_path": "/machines/plotter.svg"},
    {"machine_ref": "MCH-DIGI-01", "name": "Digital Printer", "category": "Digital Print", "capability": "Books, magazines, calendars and other digital print items", "image_path": "/machines/digital-printer.svg"},
    {"machine_ref": "MCH-BIND-01", "name": "Binder", "category": "Finishing", "capability": "Binding books", "image_path": "/machines/binder-cutter.svg"},
    {"machine_ref": "MCH-KM-01", "name": "Konica Minolta", "category": "Digital Print", "capability": "Calendars, books and normal printing", "image_path": "/machines/digital-press.svg"},
]


DEFAULT_EXPENSE_CATEGORIES = [
    {"name": "Materials", "vendor_related": True, "notes": "Paper, card stock, banner vinyl, sublimation blanks."},
    {"name": "Ink & Consumables", "vendor_related": True, "notes": "Ink sets, DTF powder/film, UV adhesive laminate."},
    {"name": "Installation", "vendor_related": True, "notes": "On-site mounting and branding installation labour."},
    {"name": "Maintenance", "vendor_related": False, "notes": "In-house technician work, service kits, drum units."},
    {"name": "Utilities", "vendor_related": False, "notes": "Electricity, water, prepaid tokens."},
    {"name": "Transport", "vendor_related": False, "notes": "Fuel reimbursement, vehicle hire."},
    {"name": "Petty Cash", "vendor_related": False, "notes": "Mirrored expenses generated by PettyCash top-ups and cash-in-hand spend."},
]


def ensure_default_machines() -> list[str]:
    existing_refs = {ref for (ref,) in db.session.query(ProductionMachine.machine_ref).all()}
    created = []
    for machine in DEFAULT_MACHINES:
        if machine["machine_ref"] in existing_refs:
            continue
        db.session.add(ProductionMachine(**machine))
        created.append(machine["machine_ref"])
    return created


def ensure_default_expense_categories() -> list[str]:
    existing_names = {name for (name,) in db.session.query(ExpenseCategory.name).all()}
    created = []
    for category in DEFAULT_EXPENSE_CATEGORIES:
        if category["name"] in existing_names:
            continue
        db.session.add(ExpenseCategory(**category))
        created.append(category["name"])
    return created


def ensure_startup_defaults() -> dict:
    created_machines = ensure_default_machines()
    created_categories = ensure_default_expense_categories()
    if created_machines or created_categories:
        db.session.commit()
        logger.info(
            "Startup defaults added: machines=%s categories=%s",
            created_machines,
            created_categories,
        )
    else:
        db.session.rollback()
    return {
        "machines": created_machines,
        "expense_categories": created_categories,
    }
