from datetime import datetime
from pathlib import Path
import csv

from flask import current_app
from openpyxl import Workbook

from ..models import Expense, ExportJob, Invoice, Job
from . import device_context


def dataset_rows(dataset):
    model_map = {
        "expenses": Expense,
        "invoices": Invoice,
        "jobs": Job,
    }
    model = model_map.get(dataset, Invoice)
    rows = [item.to_dict() for item in model.query.all()]
    return rows, dataset


def write_csv(file_path, rows):
    fieldnames = sorted({key for row in rows for key in row.keys()})
    with file_path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def write_xlsx(file_path, rows):
    workbook = Workbook()
    sheet = workbook.active
    sheet.title = "Export"
    fieldnames = sorted({key for row in rows for key in row.keys()})
    sheet.append(fieldnames)
    for row in rows:
        sheet.append([row.get(field) for field in fieldnames])
    workbook.save(file_path)


def create_export_file(dataset="financials", file_format="csv", generated_by=None):
    # Was hardcoded to "Wayne" (one specific person's name, permanently) --
    # every export ever created on any machine claimed to be generated by
    # the same one person regardless of who/which device actually triggered
    # it. Defaults to this machine's real device_id (device_context.py,
    # same identity stamped onto every other device-owned row app-wide) if
    # the caller doesn't explicitly pass a name. Falls back to "Unknown
    # Device" only in the edge case this runs before device identity is
    # set up at all (see device_context.py's own None-handling for the
    # same reasoning) -- an honest unknown, not a guessed person's name.
    #
    # Reads device_context.CURRENT_DEVICE_ID as a module attribute
    # (device_context.CURRENT_DEVICE_ID), NOT via `from .device_context
    # import CURRENT_DEVICE_ID` -- that form copies the value once at
    # import time into a separate local name, so a later
    # set_current_device_id() call (which reassigns the name inside
    # device_context's own module, via `global`) would never be seen here.
    # Same class of bug as models.py's earlier un-annotated backref: correct
    # intent, wrong binding.
    if generated_by is None:
        generated_by = device_context.CURRENT_DEVICE_ID or "Unknown Device"
    rows, dataset_name = dataset_rows(dataset)
    export_dir = Path(current_app.config["REPORT_EXPORT_DIR"])
    export_dir.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.utcnow().strftime("%Y%m%d%H%M%S")
    safe_format = file_format.lower()
    file_path = export_dir / f"{dataset_name}_{timestamp}.{safe_format}"

    if safe_format == "xlsx":
        write_xlsx(file_path, rows)
    else:
        safe_format = "csv"
        file_path = file_path.with_suffix(".csv")
        write_csv(file_path, rows)

    return ExportJob(
        export_ref=f"EXPORT-{timestamp}",
        name=f"{dataset_name.title()} Export",
        format=safe_format.upper(),
        records=len(rows),
        file_path=str(file_path),
        status="ready",
        generated_by=generated_by,
        notes="Generated from report service",
    )
