# path: backend/app/services/ref_generator.py
"""
ref_generator.py

Single, shared source for every "next reference number" function in the
app (JOB-0001, INV-0001, PROP-0001, EXP-0001, MAT-0001, ADV-0001), fixing
two real problems found by reading the actual codebase before this pass:

  1. DUPLICATION: next_job_ref(), next_invoice_ref(), and next_expense_ref()
     were each defined 2-3 times across different route/service files,
     verbatim or near-verbatim. One bug fix here now fixes every copy at
     once, instead of needing to be found and re-applied N times.

  2. COLLISION RISK (the actual reason this file exists): every one of
     those was `last.id + 1` -- fine on a single always-online device,
     but genuinely unsafe across multiple offline devices that each
     create records before ever syncing. Two devices can each look at
     their own local "last row" and independently produce "JOB-0005",
     and per the build plan's cross-device backup/restore requirement,
     those two DIFFERENT jobs would collide on merge.

FIX: every ref generated by this module includes a short per-device
fragment (from app.device_identity's device_id, set at startup via
app.services.device_context.set_current_device_id) BETWEEN the prefix
and the sequential number, e.g. "JOB-4F32-0005" instead of "JOB-0005".
Two devices can each create their own "0005" and never collide, because
their device fragments differ. A single-device install (or before a
device identity has been set at all -- see _device_fragment()'s
fallback) still gets a stable, readable ref; it just won't be the
short legacy-style "JOB-0005" anymore.

References already using uuid4() (SALE-, PAY-, PC- entry refs) are
UNCHANGED -- those were already collision-safe by construction and are
left exactly as they were, in their original files. This module only
replaces the plain-sequential ones.

Existing refs already stored in the database (old-style "JOB-0005",
etc., created before this change) are NOT touched or renamed --
changing a ref that may already be printed on a real paper invoice
would be actively harmful. This only changes what NEW refs look like
going forward.
"""

from __future__ import annotations

from . import device_context


def _device_fragment() -> str:
    """The short per-device piece inserted into every ref. Falls back to
    'LOCAL' if no device identity has been set yet (e.g. very first run,
    before main.py's startup sequence reaches set_current_device_id) --
    still produces a valid, readable ref rather than crashing ref
    generation entirely; it just won't be collision-safe against other
    devices until a device identity is actually set, which is fine
    because a not-yet-named single device has no other device to
    collide with yet.

    Reads device_context.CURRENT_DEVICE_ID via the module itself (not
    `from .device_context import CURRENT_DEVICE_ID`) -- a plain name
    import captures the value that existed at import time and never
    sees later updates from set_current_device_id(), which runs AFTER
    this module is first imported. Reading it as device_context.CURRENT_
    DEVICE_ID looks it up fresh on every call instead. (Caught by
    testing: an import-time capture here silently kept generating
    'LOCAL' refs even after the real device id was set.)
    """
    current = device_context.CURRENT_DEVICE_ID
    if not current:
        return "LOCAL"
    # device_id itself already looks like "OFFICE-PC-4F32" (see
    # device_identity.py) -- take just the short random suffix after the
    # last hyphen, so refs stay reasonably short (e.g. "JOB-4F32-0005")
    # rather than repeating the whole device name in every single ref.
    return current.rsplit("-", 1)[-1]


def _next_sequential_ref(model, prefix: str) -> str:
    """Shared implementation for every plain-sequential ref type.
    Counts existing rows FROM THIS DEVICE ONLY (not the table's overall
    last id) -- so each device's own sequence advances independently
    and predictably, rather than being affected by however many rows
    happen to exist from OTHER devices' backups already merged in.
    """
    device_fragment = _device_fragment()
    current_device_id = device_context.CURRENT_DEVICE_ID

    count = (
        model.query.filter_by(device_id=current_device_id).count()
        if current_device_id
        else model.query.filter_by(device_id=None).count()
    )
    return f"{prefix}-{device_fragment}-{(count + 1):04d}"


def next_job_ref() -> str:
    from ..models import Job
    return _next_sequential_ref(Job, "JOB")


def next_invoice_ref() -> str:
    from ..models import Invoice
    return _next_sequential_ref(Invoice, "INV")


def next_proposal_ref() -> str:
    from ..models import Proposal
    return _next_sequential_ref(Proposal, "PROP")


def next_expense_ref() -> str:
    from ..models import Expense
    return _next_sequential_ref(Expense, "EXP")


def next_material_ref() -> str:
    from ..models import Material
    return _next_sequential_ref(Material, "MAT")


def next_advance_ref() -> str:
    from ..models import Advance
    return _next_sequential_ref(Advance, "ADV")


def next_staff_ref() -> str:
    from ..models import Staff
    return _next_sequential_ref(Staff, "STAFF")


def next_client_ref() -> str:
    from ..models import Client
    return _next_sequential_ref(Client, "CLI")


def next_pricing_item_ref() -> str:
    from ..models import PricingItem
    return _next_sequential_ref(PricingItem, "PRC")


def next_material_transaction_ref() -> str:
    from ..models import MaterialTransaction
    return _next_sequential_ref(MaterialTransaction, "MTX")