# path: backend/app/routes/expenses.py

from flask import Blueprint, jsonify, request

from ..extensions import db
from ..models import AuditLog, Expense, ExpenseCategory
from ..services.expenses import sync_expense_status
from ..services.ref_generator import next_expense_ref
from ..utils import parse_date
from .common import apply_search, list_response

bp = Blueprint("expenses", __name__)


@bp.get("/categories")
def list_expense_categories():
    # Item 4 (Prompt 6): the Expense modal needs to know which categories are
    # vendor-related to conditionally show the vendor picker. Expense.category
    # stays a free-text string (per services/expenses.py's docstring), so this
    # is a simple lookup-table read, not tied to any individual Expense row.
    categories = ExpenseCategory.query.order_by(ExpenseCategory.name.asc()).all()
    return jsonify({"items": [category.to_dict() for category in categories]})


# The 7 real categories this business actually uses - same list seed.py's
# full mock-data seeder creates, pulled out on its own here. seed.py also
# seeds fake demo clients/invoices/jobs alongside these, which is fine for
# a fresh dev database but not something to run against a real install just
# to populate categories - nothing else in the app calls seed.py, so on an
# install where these rows never got created (e.g. a reset or fresh DB),
# there was previously no way to get them back except a manual DB edit.
REAL_EXPENSE_CATEGORIES = [
    {"name": "Materials", "vendor_related": True, "notes": "Paper, card stock, banner vinyl, sublimation blanks."},
    {"name": "Ink & Consumables", "vendor_related": True, "notes": "Ink sets, DTF powder/film, UV adhesive laminate."},
    {"name": "Installation", "vendor_related": True, "notes": "On-site mounting and branding installation labour."},
    {"name": "Maintenance", "vendor_related": False, "notes": "In-house technician work, service kits, drum units."},
    {"name": "Utilities", "vendor_related": False, "notes": "Electricity, water, prepaid tokens."},
    {"name": "Transport", "vendor_related": False, "notes": "Fuel reimbursement, vehicle hire."},
    {"name": "Petty Cash", "vendor_related": False, "notes": "Mirrored expenses generated by PettyCash top-ups and cash-in-hand spend."},
]


@bp.post("/categories/seed")
def seed_expense_categories():
    # Idempotent by design - safe to call more than once. Only inserts
    # categories that don't already exist by name; never touches or
    # duplicates existing rows, so this can't be used to reset/wipe
    # categories, only to fill in ones that are missing.
    existing_names = {name for (name,) in db.session.query(ExpenseCategory.name).all()}
    created = []
    for category in REAL_EXPENSE_CATEGORIES:
        if category["name"] in existing_names:
            continue
        row = ExpenseCategory(**category)
        db.session.add(row)
        created.append(category["name"])
    db.session.commit()
    return jsonify({"created": created, "already_present": sorted(existing_names)})


def serialize_expense(expense):
    # Mirrors routes/jobs.py::serialize_job()'s machine_name join pattern —
    # keeps Expense.to_dict() (SerializableMixin) generic and adds the joined
    # field at the route/serializer layer instead. vendor_id is nullable, so
    # vendor-less expenses (utilities, fuel, etc.) return vendor_name: null
    # and the frontend's existing fallback chain handles that case.
    return expense.to_dict() | {
        "vendor_name": expense.vendor.name if expense.vendor else None,
        "category_vendor_related": bool(expense.expense_category and expense.expense_category.vendor_related),
        # Item 19 follow-up: editing a petty-cash-generated expense's amount
        # here was meant to push the change back to its linked PettyCash
        # entry (see update_expense() below), but per explicit instruction
        # the simpler, safer fix is blocking the edit outright instead of
        # trusting a two-way sync - Petty Cash is the source of truth for
        # these, edited from the Petty Cash page only. The frontend needs
        # this flag to know which rows to lock.
        "is_petty_cash_linked": expense.petty_cash_source is not None,
    }


@bp.get("")
def list_expenses():
    query = Expense.query
    status = request.args.get("status")
    if status and status.lower() != "all":
        query = query.filter(Expense.status == status.lower())
    query = apply_search(query, Expense, ["expense_ref", "category", "title", "submitted_by"])
    return jsonify(list_response(query.order_by(Expense.expense_date.desc()), serialize_expense))


@bp.post("")
def create_expense():
    data = request.get_json() or {}
    expense = Expense(
        expense_ref=data.get("expense_ref") or next_expense_ref(),
        vendor_id=data.get("vendor_id"),
        category=data["category"],
        category_id=data.get("category_id"),
        title=data["title"],
        amount=data.get("amount", 0),
        expense_date=parse_date(data["expense_date"]),
        paid_on=parse_date(data.get("paid_on")),
        status=data.get("status", "pending"),
        submitted_by=data.get("submitted_by"),
        notes=data.get("notes"),
    )
    if expense.paid_on:
        sync_expense_status(expense)
    db.session.add(expense)
    db.session.flush()
    db.session.add(AuditLog(action=f"Created expense {expense.expense_ref}", entity_type="expense", entity_id=expense.id))
    db.session.commit()
    return jsonify(serialize_expense(expense)), 201


@bp.put("/<int:expense_id>")
def update_expense(expense_id):
    expense = Expense.query.get_or_404(expense_id)
    data = request.get_json() or {}
    # Item 19 follow-up: an expense generated from a Petty Cash entry
    # (services/petty_cash.py) is a mirror of that entry, not an independent
    # record - editing it here used to push amount changes back to the
    # linked PettyCash row, but per explicit instruction the safer fix is
    # blocking the edit outright rather than trusting a two-way sync. Petty
    # Cash stays the single source of truth; edit the entry there instead.
    if expense.petty_cash_source is not None:
        return jsonify({
            "error": "This expense was created from a Petty Cash entry and can only be edited from the Petty Cash page.",
        }), 409
    for field in ["vendor_id", "category", "category_id", "title", "amount", "status", "submitted_by", "notes"]:
        if field in data:
            setattr(expense, field, data[field])
    # Prompt 6 item 4: allow explicitly clearing the vendor link (e.g. user
    # switches to a non-vendor-related category after picking a vendor).
    if "vendor_id" in data and data["vendor_id"] is None:
        expense.vendor_id = None
    if "expense_date" in data:
        expense.expense_date = parse_date(data.get("expense_date"))
    if "paid_on" in data:
        expense.paid_on = parse_date(data.get("paid_on"))
        sync_expense_status(expense)
    db.session.add(AuditLog(action=f"Updated expense {expense.expense_ref}", entity_type="expense", entity_id=expense.id))
    db.session.commit()
    return jsonify(serialize_expense(expense))